// src/config.js
export const puppeteerOptions = {
    defaultViewport: {
        width: 1000,
        height: 800,
    },
    headless: false,
    userDataDir: "tmp/gpc_order_spider_usr_dir3",
    args: [
        '--no-sandbox',
        '--disable-client-side-phishing-detection',
        '--disable-setuid-sandbox',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-popup-blocking',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-speech-api',
        '--hide-scrollbars',
        '--mute-audio',
        '--disable-extensions',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-default-browser-check',
        '--no-pings',
        '--password-store=basic',
        '--use-mock-keychain',
        '--no-zygote',
    ],
};
